FROM node:20-alpine

WORKDIR /app

# Copiar todo el monorepo
COPY . .

# Instalar dependencias
RUN npm install

# Exponer puerto
EXPOSE 3000

# Comando para iniciar el backend
CMD ["node", "packages/mc-back/index.js"]
