FROM node:20-alpine

WORKDIR /app

# Copiar todo el monorepo
COPY . .

# Instalar dependencias
RUN npm install

# Exponer puerto
EXPOSE 8000

# Comando para iniciar el frontend
CMD ["npm", "run", "serve", "--workspace=packages/mc-frontend", "--", "--host", "0.0.0.0", "--port", "8000"]
