export const PLACE_ASIDE_MATCH = 'ASIDE_MATCH';
export const PLACE_ENCOUNTER_DECK = 'ENCOUNTER_DECK';
export const PLACE_ENCOUNTER_DECK_CARDS = 'ENCOUNTER_DECK_CARDS';
export const PLACE_ENCOUNTER_DISCARD = 'ENCOUNTER_DISCARD';
export const PLACE_OUTSIDE_NEMESIS = 'OUTSIDE_NEMESIS';
export const PLACE_SCENARIO_ZONE = 'SCENARIO_ZONE';
